version: '3'

services:
  app:
    build: .
    tty: true
    volumes:
      - ../app:/app
    # warning: to use gdb
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined
